export const callbackData = {
    GESAR_EPOS:             "gesar_epos",
    ZOV_DOBRA:              "zov_dobra",
    TABLE_OF_CONTENTS:      "table_of_contents",
    START_QUEST:            "start_quest",
    ADD_KARMA:              "add_karma",
    GESAR_EPOS_DESCR:       "gesar_epos_descr",
    BECOMING:               "becoming",
    BACK_TO_START:          "back_to_start",
    BACK_TO_START_HARD:     "back_to_start_hard",
    BACK_TO_QUEST_START:    "back_to_quest_start",
    QUEST_END:              "quest_end",

    // PART 1
    GESAR_PART1_1:          "gesar:part1:1",
    GESAR_PART1_2_1:        "gesar:part1:2:1",
    GESAR_PART1_2_2:        "gesar:part1:2:2",
    GESAR_PART1_3:          "gesar:part1:3",
    GESAR_PART1_TEST_0:     "gesar:part1:test:0",
    GESAR_PART1_TEST_1:     "gesar:part1:test:1",
    GESAR_PART1_TEST_no:    "gesar:part1:test:no",
    GESAR_PART1_TEST_1_yes: "gesar:part1:test:1:yes",
    GESAR_PART1_TEST_2:     "gesar:part1:test:2",
    GESAR_PART1_TEST_2_yes: "gesar:part1:test:2:yes",

    // PART 2
    GESAR_PART2_1_1:        "gesar_part2_1_1",
    GESAR_PART2_1_2:        "gesar_part2_1_2",
    GESAR_PART2_2_1:        "gesar_part2_2_1",
    GESAR_PART2_2_2:        "gesar_part2_2_2",
    GESAR_PART2_3_1:        "gesar_part2_3_1",
    GESAR_PART2_3_2:        "gesar_part2_3_2",
    GESAR_PART2_4_1:        "gesar_part2_4_1",
    GESAR_PART2_4_2:        "gesar_part2_4_2",
    GESAR_PART2_TEST_0:     "gesar_part2_test_0",
    GESAR_PART2_TEST_1:     "gesar_part2_test_1",
    GESAR_PART2_TEST_no:    "gesar_part2_test_no",
    GESAR_PART2_TEST_1_yes: "gesar_part2_test_1_yes",
    GESAR_PART2_TEST_2:     "gesar_part2_test_2",
    GESAR_PART2_TEST_2_yes: "gesar_part2_test_2_yes",

    // PART 3
    GESAR_PART3_1_1:        "gesar_part3_1_1",
    GESAR_PART3_1_2:        "gesar_part3_1_2",
    GESAR_PART3_2_1:        "gesar_part3_2_1",
    GESAR_PART3_2_2:        "gesar_part3_2_2",
    GESAR_PART3_3_1:        "gesar_part3_3_1",
    GESAR_PART3_3_2:        "gesar_part3_3_2",
    GESAR_PART3_3_3:        "gesar_part3_3_3",
    GESAR_PART3_TEST_0:     "gesar_part3_test_0",
    GESAR_PART3_TEST_1:     "gesar_part3_test_1",
    GESAR_PART3_TEST_no:    "gesar_part3_test_no",
    GESAR_PART3_TEST_1_yes: "gesar_part3_test_1_yes",
    GESAR_PART3_TEST_2:     "gesar_part3_test_2",
    GESAR_PART3_TEST_2_yes: "gesar_part3_test_2_yes",

    // PART 4
    GESAR_PART4_1_1:        "gesar_part4_1_1",
    GESAR_PART4_1_2:        "gesar_part4_1_2",
    GESAR_PART4_2_1:        "gesar_part4_2_1",
    GESAR_PART4_2_2:        "gesar_part4_2_2",
    GESAR_PART4_3_1:        "gesar_part4_3_1",
    GESAR_PART4_3_2:        "gesar_part4_3_2",
    GESAR_PART4_4_1:        "gesar_part4_4_1",
    GESAR_PART4_4_2:        "gesar_part4_4_2",
    GESAR_PART4_TEST_0:     "gesar_part4_test_0",
    GESAR_PART4_TEST_1:     "gesar_part4_test_1",
    GESAR_PART4_TEST_no:    "gesar_part4_test_no",
    GESAR_PART4_TEST_1_yes: "gesar_part4_test_1_yes",
    GESAR_PART4_TEST_2:     "gesar_part4_test_2",
    GESAR_PART4_TEST_2_yes: "gesar_part4_test_2_yes",
}