export const callbackData = {
    GESAR_EPOS:             "gesar_epos",
    ZOV_DOBRA:              "zov_dobra",
    TABLE_OF_CONTENTS:      "table_of_contents",
    START_QUEST:            "start_quest",
    ADD_KARMA:              "add_karma",
    GESAR_EPOS_DESCR:       "gesar_epos_descr",
    BECOMING:               "becoming",
    BACK_TO_START:          "back_to_start",
    BACK_TO_START_HARD:     "back_to_start_hard",
    BACK_TO_QUEST_START:    "back_to_quest_start",
    QUEST_END:              "quest_end",

    // PART 1
    GESAR_PART1_1:          "gesar:part1:1",
    GESAR_PART1_2_1:        "gesar:part1:2:1",
    GESAR_PART1_2_2:        "gesar:part1:2:2",
    GESAR_PART1_3:          "gesar:part1:3",
    GESAR_PART1_TEST_0:     "gesar:part1:test:0",
    GESAR_PART1_TEST_1:     "gesar:part1:test:1",
    GESAR_PART1_TEST_no:    "gesar:part1:test:no",
    GESAR_PART1_TEST_1_yes: "gesar:part1:test:1:yes",
    GESAR_PART1_TEST_2:     "gesar:part1:test:2",
    GESAR_PART1_TEST_2_yes: "gesar:part1:test:2:yes",

    // PART 2
    GESAR_PART2_1_1:        "gesar:part2:1:1",
    GESAR_PART2_1_2:        "gesar:part2:1:2",
    GESAR_PART2_2_1:        "gesar:part2:2:1",
    GESAR_PART2_2_2:        "gesar:part2:2:2",
    GESAR_PART2_3_1:        "gesar:part2:3:1",
    GESAR_PART2_3_2:        "gesar:part2:3:2",
    GESAR_PART2_4_1:        "gesar:part2:4:1",
    GESAR_PART2_4_2:        "gesar:part2:4:2",
    GESAR_PART2_TEST_0:     "gesar:part2:test:0",
    GESAR_PART2_TEST_1:     "gesar:part2:test:1",
    GESAR_PART2_TEST_no:    "gesar:part2:test:no",
    GESAR_PART2_TEST_1_yes: "gesar:part2:test:1:yes",
    GESAR_PART2_TEST_2:     "gesar:part2:test:2",
    GESAR_PART2_TEST_2_yes: "gesar:part2:test:2:yes",

    // PART 3
    GESAR_PART3_1_1:        "gesar:part3:1:1",
    GESAR_PART3_1_2:        "gesar:part3:1:2",
    GESAR_PART3_2_1:        "gesar:part3:2:1",
    GESAR_PART3_2_2:        "gesar:part3:2:2",
    GESAR_PART3_3_1:        "gesar:part3:3:1",
    GESAR_PART3_3_2:        "gesar:part3:3:2",
    GESAR_PART3_3_3:        "gesar:part3:3:3",
    GESAR_PART3_TEST_0:     "gesar:part3:test:0",
    GESAR_PART3_TEST_1:     "gesar:part3:test:1",
    GESAR_PART3_TEST_no:    "gesar:part3:test:no",
    GESAR_PART3_TEST_1_yes: "gesar:part3:test:1:yes",
    GESAR_PART3_TEST_2:     "gesar:part3:test:2",
    GESAR_PART3_TEST_2_yes: "gesar:part3:test:2:yes",

    // PART 4
    GESAR_PART4_1_1:        "gesar:part4:1:1",
    GESAR_PART4_1_2:        "gesar:part4:1:2",
    GESAR_PART4_2_1:        "gesar:part4:2:1",
    GESAR_PART4_2_2:        "gesar:part4:2:2",
    GESAR_PART4_3_1:        "gesar:part4:3:1",
    GESAR_PART4_3_2:        "gesar:part4:3:2",
    GESAR_PART4_4_1:        "gesar:part4:4:1",
    GESAR_PART4_4_2:        "gesar:part4:4:2",
    GESAR_PART4_TEST_0:     "gesar:part4:test:0",
    GESAR_PART4_TEST_1:     "gesar:part4:test:1",
    GESAR_PART4_TEST_no:    "gesar:part4:test:no",
    GESAR_PART4_TEST_1_yes: "gesar:part4:test:1:yes",
    GESAR_PART4_TEST_2:     "gesar:part4:test:2",
    GESAR_PART4_TEST_2_yes: "gesar:part4:test:2:yes",

    // PART 5
    GESAR_PART5_1_1:        "gesar:part5:1:1",
    GESAR_PART5_1_2:        "gesar:part5:1:2",
    GESAR_PART5_2_1:        "gesar:part5:2:1",
    GESAR_PART5_2_2:        "gesar:part5:2:2",
    GESAR_PART5_3_1:        "gesar:part5:3:1",
    GESAR_PART5_3_2:        "gesar:part5:3:2",
    GESAR_PART5_TEST_0:     "gesar:part5:test:0",
    GESAR_PART5_TEST_1:     "gesar:part5:test:1",
    GESAR_PART5_TEST_no:    "gesar:part5:test:no",
    GESAR_PART5_TEST_1_yes: "gesar:part5:test:1:yes",
    GESAR_PART5_TEST_2:     "gesar:part5:test:2",
    GESAR_PART5_TEST_2_yes: "gesar:part5:test:2:yes",

    // PART 6
    GESAR_PART6_1_1:        "gesar:part6:1:1",
    GESAR_PART6_1_2:        "gesar:part6:1:2",
    GESAR_PART6_2_1:        "gesar:part6:2:1",
    GESAR_PART6_2_2:        "gesar:part6:2:2",
    GESAR_PART6_3_1:        "gesar:part6:3:1",
    GESAR_PART6_3_2:        "gesar:part6:3:2",
    GESAR_PART6_TEST_0:     "gesar:part6:test:0",
    GESAR_PART6_TEST_1:     "gesar:part6:test:1",
    GESAR_PART6_TEST_no:    "gesar:part6:test:no",
    GESAR_PART6_TEST_1_yes: "gesar:part6:test:1:yes",
    GESAR_PART6_TEST_2:     "gesar:part6:test:2",
    GESAR_PART6_TEST_2_yes: "gesar:part6:test:2:yes",

    // PART 7
    GESAR_PART7_1_1:        "gesar:part7:1:1",
    GESAR_PART7_1_2:        "gesar:part7:1:2",
    GESAR_PART7_1_3:        "gesar:part7:1:3",
    GESAR_PART7_2_1:        "gesar:part7:2:1",
    GESAR_PART7_2_2:        "gesar:part7:2:2",
    GESAR_PART7_3_1:        "gesar:part7:3:1",
    GESAR_PART7_3_2:        "gesar:part7:3:2",
    GESAR_PART7_4_1:        "gesar:part7:4:1",
    GESAR_PART7_4_2:        "gesar:part7:4:2",
    GESAR_PART7_4_3:        "gesar:part7:4:3",
    GESAR_PART7_TEST_0:     "gesar:part7:test:0",
    GESAR_PART7_TEST_1:     "gesar:part7:test:1",
    GESAR_PART7_TEST_no:    "gesar:part7:test:no",
    GESAR_PART7_TEST_1_yes: "gesar:part7:test:1:yes",
    GESAR_PART7_TEST_2:     "gesar:part7:test:2",
    GESAR_PART7_TEST_2_yes: "gesar:part7:test:2:yes",
}